name: Reusable Print Environment Variable

on:
  workflow_call:
  dispatch:

jobs:
  print-env:
    runs-on: ubuntu-latest
    steps:
      - name: Print environment variable
        run: echo ${{ env.VAR }}
