name: Reusable Print Environment Variable

on:
  workflow_call:
    # Map the workflow outputs to job outputs
    inputs:
      VAR:
        required: true

jobs:
  my-dynamic-env-job:
    runs-on: ubuntu-latest
    environment: production
    steps:
      - run: |
          echo "${{ vars.VAR }}"