name: Reusable Print Environment Variable

on:
  workflow_call:
    inputs:
      VAR:
        description: 'The environment variable to print'
        required: true
        type: string
  workflow_dispatch:

jobs:
  my-dynamic-env-job:
    runs-on: ubuntu-latest
    environment: production
    steps:
      - run: |
          echo "${{ vars.VAR }}"