name: Deploy AWS Infrastructure

on:
  workflow_call:
    inputs:
      stage:
        description: 'Deployment stage (e.g., development, staging, production)'
        required: true
        type: string
      ecr_repository:
        description: 'ECR repository name for the application.'
        required: false
        type: string
      release_version:
        required: true
        type: string
      working_directory:
        description: 'Path to the Terraform configuration files.'
        required: false
        type: string
        default: 'infrastructure'
    secrets:
      AWS_ACCESS_KEY_ID:
        required: true
      AWS_SECRET_ACCESS_KEY:
        required: true

permissions: write-all


defaults:
  run:
    shell: bash
    working-directory: ${{ inputs.working_directory }}

env:
  AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
  AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
  AWS_REGION: "us-east-2"

jobs:
  terraform-aws:
    name: Deploy Terraform
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v4

      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v3

      - name: Terraform Init
        id: init
        run: terraform init -upgrade

      - name: Terraform Workspace Select
        run: terraform workspace select -or-create ${{ inputs.stage }}

      - name: Terraform Validate
        id: validate
        run: terraform validate

      - name: Get AWS identity
        id: aws_identity
        run: aws sts get-caller-identity

      - name: Terraform Apply
        id: apply
        envs:
          TF_VAR_aws_access_key: ${{ secrets.AWS_ACCESS_KEY_ID }}
          TF_VAR_aws_secret_key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          TF_VAR_commit_sha: ${{ github.sha }}
          TF_VAR_release_version: ${{ inputs.release_version }}
        run: terraform apply -auto-approve -var-file="${{ inputs.stage }}.tfvars"  -input=false
